export const faqData = [
  {
    id: "1",
    title: "How to Create an Event on WomenHub",
    date: "May 8, 2024",
    status: "PUBLISHED",
    editor: `Editor s Name`,
    category: "Health",
  },
  {
    id: "2",
    title: "Changing your email address on women hub",
    date: "May 8, 2024",
    status: "DRAFT",
    editor: `Editor s Name`,
    category: "Health",
  },
  {
    id: "3",
    title: "Editing a projectfrom my dashboard",
    date: "May 8, 2024",
    status: "ARCHIVED",
    editor: `Editor s Name`,
    category: "Travel",
  },
  {
    id: "4",
    title: "How to Create an organization on WomenHu",
    date: "May 8, 2024",
    status: "PUBLISHED",
    editor: `Editor s Name`,
    category: "Health",
  },
  {
    id: "5",
    title: "How to Create an organization on WomenHu",
    date: "May 8, 2024",
    status: "PUBLISHED",
    editor: `Editor s Name`,
    category: "Programming",
  },
  {
    id: "6",
    title: "How to Create an organization on WomenHu",
    date: "May 8, 2024",
    status: "PUBLISHED",
    editor: `Editor s Name`,
    category: "Health",
  },
  {
    id: "7",
    title: "test",
    date: "May 8, 2024",
    status: "PUBLISHED",
    editor: `Editor s Name`,
    category: "Books",
  },
  {
    id: "8",
    title: "How to Create an organization on WomenHu",
    date: "May 8, 2024",
    status: "PUBLISHED",
    editor: `Editor s Name`,
    category: "Fitness",
  },
];
