export const postData = [
  {
    id: 1,
    title: 'Introduction to JavaScript',
    description: 'Learn the basics of JavaScript programming language.',
    coverImageUrl: 'js-intro.jpg',
    datePublished: '2023-05-15',
    author: 'John Doe',
    category: { name: 'Programming' },
    tags: 'JavaScript, Programming Basics',
    numberOfComments: 12,
    numberOfLikes: 28,
    status: 'PUBLISHED',
  },
  {
    id: 2,
    title: 'Healthy Eating Tips',
    description: 'Discover simple tips for maintaining a healthy diet.',
    coverImageUrl: 'healthy-eating.jpg',
    datePublished: '2023-06-02',
    author: 'Jane Smith',
    category: { name: 'Health' },
    tags: 'Nutrition, Wellness',
    numberOfComments: 8,
    numberOfLikes: 16,
    status: 'DRAFT',
  },
  {
    id: 3,
    title: 'Travel Guide: Paris',
    description: 'Explore the best places to visit in Paris, France.',
    coverImageUrl: 'paris-travel.jpg',
    datePublished: '2023-04-20',
    author: 'Emily Brown',
    category: { name: 'Travel' },
    tags: 'Paris, Travel Tips',
    numberOfComments: 15,
    numberOfLikes: 32,
    status: 'PUBLISHED',
  },
  {
    id: 4,
    title: 'Book Review: The Great Gatsby',
    description: "A review of F. Scott Fitzgerald's classic novel.",
    coverImageUrl: 'gatsby-book.jpg',
    datePublished: '2023-07-10',
    author: 'Michael Johnson',
    category: { name: 'Books' },
    tags: 'Literature, Book Reviews',
    numberOfComments: 5,
    numberOfLikes: 20,
    status: 'DRAFT',
  },
  {
    id: 5,
    title: 'Fitness Tips: Strength Training',
    description: 'Effective strength training exercises for beginners.',
    coverImageUrl: 'strength-training.jpg',
    datePublished: '2023-05-28',
    author: 'Alex Davis',
    category: { name: 'Fitness' },
    tags: 'Exercise, Fitness Tips',
    numberOfComments: 10,
    numberOfLikes: 25,
    status: 'PUBLISHED',
  },
];
