export const faqData = [
  {
    id: "1",
    title: "How to Create an Event on WomenHub",
    date: "May 8, 2024",
    status: "Published",
    editor: `Editor s Name`,
  },
  {
    id: "2",
    title: "Changing your email address on women hub",
    date: "May 8, 2024",
    status: "Published",
    editor: `Editor s Name`,
  },
  {
    id: "3",
    title: "Editing a projectfrom my dashboard",
    date: "May 8, 2024",
    status: "Published",
    editor: `Editor s Name`,
  },
  {
    id: "4",
    title: "How to Create an organization on WomenHu",
    date: "May 8, 2024",
    status: "Published",
    editor: `Editor s Name`,
  },
  {
    id: "5",
    title: "How to Create an organization on WomenHu",
    date: "May 8, 2024",
    status: "Published",
    editor: `Editor s Name`,
  },
  {
    id: "6",
    title: "How to Create an organization on WomenHu",
    date: "May 8, 2024",
    status: "Published",
    editor: `Editor s Name`,
  },
  {
    id: "7",
    title: "test",
    date: "May 8, 2024",
    status: "Published",
    editor: `Editor s Name`,
  },
  {
    id: "8",
    title: "How to Create an organization on WomenHu",
    date: "May 8, 2024",
    status: "Published",
    editor: `Editor s Name`,
  },
];
