export const guideData = [
  {
    id: "1",
    title: "How to Create an organization on WomenHu",
    image: "test.jn",
    date: "May 8, 2024",
    status: "Published",
    editor: `Editor s Name`,
  },
  {
    id: "2",
    title: "How to Create an organization on WomenHu",
    image: "test.jn",
    date: "May 8, 2024",
    status: "Published",
    editor: `Editor s Name`,
  },
  {
    id: "3",
    title: "How to Create an organization on WomenHu",
    image: "test.jn",
    date: "May 8, 2024",
    status: "Published",
    editor: `Editor s Name`,
  },
  {
    id: "4",
    title: "How to Create an organization on WomenHu",
    image: "test.jn",
    date: "May 8, 2024",
    status: "Published",
    editor: `Editor s Name`,
  },
  {
    id: "5",
    title: "How to Create an organization on WomenHu",
    image: "test.jn",
    date: "May 8, 2024",
    status: "Published",
    editor: `Editor s Name`,
  },
  {
    id: "6",
    title: "How to Create an organization on WomenHu",
    image: "test.jn",
    date: "May 8, 2024",
    status: "Published",
    editor: `Editor s Name`,
  },
  {
    id: "7",
    title: "test",
    image: "test.jn",
    date: "May 8, 2024",
    status: "Published",
    editor: `Editor s Name`,
  },
  {
    id: "8",
    title: "How to Create an organization on WomenHu",
    image: "test.jn",
    date: "May 8, 2024",
    status: "Published",
    editor: `Editor s Name`,
  },
];
